### ISSUE TITLE
Click cancel and the delete button keeps loading

### ISSUE THREAD

**Issue by panlina** [tuanddd/grru#10]
Click delete button, then click cancel in the confirmation dialog, I get this:
<img width="149" alt="image" src="https://user-images.githubusercontent.com/18240847/121995363-60c43200-cdd9-11eb-9292-2c9120aaa0f5.png">
Gitlab version: 12.10.14-ee

**Comment by tuanddd** [comment]
HI @panlina, seems like it's just a matter of changing the button back to the normal state if the user hits cancel. So nothing is really running behind the scene :)

Will include it in subsequent release.

**Comment by panlina** [comment]
Thanks. Really helpful tool. :)

**Comment by tuanddd** [comment]
@panlina this is fixed in v1.1.2 :)
