### ISSUE TITLE
Manifest is missing or unreadable on OSX.

### ISSUE THREAD

**Issue by jackjansen** [tuanddd/grru#2]
Trying to load into Chrome on OSX `Version 88.0.4324.27 (Official Build) beta (x86_64)`, downloaded and unpacked the guru zip, followed the instructions and I get the error `Manifest is missing or unreadable`.

**Comment by tuanddd** [comment]
Hi @jackjansen, can you redownload the latest build file [here](https://github.com/tuanddd/grru/releases/download/v1.1.0/build.zip) and try again.

If the error still exist, check that a `manifest.json` file is present and paste its content here.

Thanks ;)

**Comment by tuanddd** [comment]
Hi @jackjansen any updates or blockers that I can help with?

**Comment by jackjansen** [comment]
This issue has been solved. 

(unfortunately it turns out that somehow the extension doesn't work for me, probably because the gitlab I want to use it on is running on a nonstandard https port. But that's a different issue).
