### ISSUE TITLE
Script doesn't work if your gitlab has multiple levels of groups

### ISSUE THREAD

**Issue by jackjansen** [tuanddd/grru#3]
I presume that if there is one level of groups the script works, but on the gitlab I've tried it on we use multiple levels of groups:

```
toplevelgroup/subgroup1/project1
```

The script fails because it tries to retrieve 

```
https://gitlab.example.com:9999/api/v4/projects/toplevelgroup%2Fsubgroup1/members/all
```

in stead of

```
https://gitlab.example.com:9999/api/v4/projects/toplevelgroup%2Fsubgroup1%2Fproject1/members/all
```

**Comment by tuanddd** [comment]
Ah yes sorry I've not seen this case before but I will release a new version soon 🙂

**Comment by tuanddd** [comment]
Hi @jackjansen, I've submited a build to address your issue, can you come over to #4 and checkout the build, test it and verify that it works. Then I'll merge and release a new version 🤝

Thanks.

**Comment by jackjansen** [comment]
Brilliant! Works as expected, thanks a lot!
